# Creating an environment: conda env create --file nf_base_environment.yml
# Updating an environment: conda env update --file nf_base_environment.yml
name: nf_base
dependencies:
  - python=3.8.5
  - pip
  #- jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pytest
  - pytest-mock
  - scipy
  - seaborn
  - statsmodels
  - nb_conda
  - altair
  - scikit-learn
